import Head from "next/head";
import { Container } from "src/styles/pages/home";

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Atque
        consectetur, ipsa inventore saepe earum voluptatibus animi quisquam rem
        minus odio dolore omnis sed ullam iusto ex quam sint quia consequuntur.
      </Container>
    </>
  );
}

export default Home;
